package br.com.altamira.wbccad.repository;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import br.com.altamira.wbccad.model.OrcMat;
import br.com.altamira.wbccad.model.OrcMatPK;

@Repository
@Transactional(readOnly = true)
public interface OrcMatRepository extends CrudRepository<OrcMat, OrcMatPK> {

    List<OrcMat> findAllByIdNumeroOrcamento(String orcamento);
    
    List<OrcMat> findAllByIdNumeroOrcamentoAndOrcMatGrupoAndOrcMatSubGrupo(String orcamento, Integer grupo, String subgrupo);

    @Query(value = "SELECT :orcamento AS [numeroOrcamento],0 AS [COMISSAO_FATOR],0 AS [ENCARGOS_VALOR],0 AS [FreteValor],0 AS [IcmsBase],0 AS [IcmsFator],0 AS [IcmsRedutor],0 AS [IcmsValor],0 AS [IpiBase],0 AS [IpiFator],0 AS [IpiValor],0 AS [MontagemValor],NULL AS [NATUREZA],ORCDET.ORCDET_CODIGO AS [orcmat_codigo],MIN(ORCDET.ORCDET_CODIGO_ORI) AS [orcmat_codigo_pai],NULL AS [orcmat_cor],MIN(ORCDET.ORCDET_ACESSORIO) AS [orcmat_descricao],'' AS [ORCMAT_FORNECEDOR],NULL AS [ORCMAT_IDMDESCRICAO],NULL AS [ORCMAT_IDMUNIDADE],ORCDET.ORCDET_PESO AS [orcmat_peso],ORCDET_PRC_ALTURA AS [ORCMAT_PRC_ALTURA],ORCDET_PRC_COMPRIMENTO AS [ORCMAT_PRC_COMPRIMENTO],NULL AS [ORCMAT_PRC_FORMULA],NULL AS [ORCMAT_SEMCENTAVOS],ORCDET_PRC_LARGURA AS [ORCMAT_PRC_LARGURA],'' AS [ORCMAT_PRDUNIDADE],0 AS [orcmat_preco],0 AS [orcmat_preco_lista],0 AS [orcmat_preco_lista_sem],0 AS [ORCMAT_PRECO_TAB],SUM(ORCDET.ORCDET_QTDE) AS [orcmat_qtde],[ORCDET_ALTURA]*[ORCDET_PRC_ALTURA] AS [ORCMATALTURA],MIN(ORCDET.ORCDETBASE) AS [orcmatbase],[ORCDET_COMPRIMENTO]*[ORCDET_PRC_COMPRIMENTO] AS [ORCMATCOMPRIMENTO],ORCDET.ORCDETCORPESQUISA AS [OrcMatCorPesquisa],NULL AS [ORCMATDESCONTO],MIN(ORCDET.ORCDET_GRUPO) AS [OrcMatGrupo],[ORCDET_PROFUNDIDADE]*[ORCDET_PRC_LARGURA] AS [ORCMATLARGURA],NULL AS [orcmatlista],NULL AS [ORCMATSITUACAO],MIN(ORCDET.ORCDET_SUBGRUPO) AS [OrcMatSubGrupo],NULL AS [PISCOFINSFATOR],NULL AS [PISCOFINSVALOR],NULL AS [PRDORCCHK],NULL AS [preco_fixo],0 AS [PISFATOR],0 AS [COFINSFATOR],NULL AS [ROYALTIES_CALCULO],NULL AS [CUSTO_CALCULO],NULL AS [REPASSE_CALCULO],NULL AS [FRETE_CALCULO],NULL AS [INDICE_COMPRA],NULL AS [INDICE_FATURAMENTO],NULL AS [IPI_NAO_INCLUSO],ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS ORCMAT_COUNTER FROM ORCDET WHERE ORCDET.NUMEROORCAMENTO = :orcamento GROUP BY ORCDET.NUMEROORCAMENTO, ORCDET.ORCDET_CODIGO, ORCDET.ORCDETCORPESQUISA, ORCDET.ORCDET_PESO, [ORCDET_COMPRIMENTO]*[ORCDET_PRC_COMPRIMENTO], [ORCDET_ALTURA]*[ORCDET_PRC_ALTURA], [ORCDET_PROFUNDIDADE]*[ORCDET_PRC_LARGURA], ORCDET.ORCDETBASE, ORCDET_PRC_COMPRIMENTO, ORCDET_PRC_ALTURA, ORCDET_PRC_LARGURA", nativeQuery=true)
    List<OrcMat> findAllByNumeroOrcamento(@Param("orcamento") String orcamento);
    
    @Query(value = "SELECT :orcamento AS [numeroOrcamento],0 AS [COMISSAO_FATOR],0 AS [ENCARGOS_VALOR],0 AS [FreteValor],0 AS [IcmsBase],0 AS [IcmsFator],0 AS [IcmsRedutor],0 AS [IcmsValor],0 AS [IpiBase],0 AS [IpiFator],0 AS [IpiValor],0 AS [MontagemValor],NULL AS [NATUREZA],ORCDET.ORCDET_CODIGO AS [orcmat_codigo],MIN(ORCDET.ORCDET_CODIGO_ORI) AS [orcmat_codigo_pai],NULL AS [orcmat_cor],MIN(ORCDET.ORCDET_ACESSORIO) AS [orcmat_descricao],'' AS [ORCMAT_FORNECEDOR],NULL AS [ORCMAT_IDMDESCRICAO],NULL AS [ORCMAT_IDMUNIDADE],ORCDET.ORCDET_PESO AS [orcmat_peso],ORCDET_PRC_ALTURA AS [ORCMAT_PRC_ALTURA],ORCDET_PRC_COMPRIMENTO AS [ORCMAT_PRC_COMPRIMENTO],NULL AS [ORCMAT_PRC_FORMULA],NULL AS [ORCMAT_SEMCENTAVOS],ORCDET_PRC_LARGURA AS [ORCMAT_PRC_LARGURA],'' AS [ORCMAT_PRDUNIDADE],0 AS [orcmat_preco],0 AS [orcmat_preco_lista],0 AS [orcmat_preco_lista_sem],0 AS [ORCMAT_PRECO_TAB],SUM(ORCDET.ORCDET_QTDE) AS [orcmat_qtde],[ORCDET_ALTURA]*[ORCDET_PRC_ALTURA] AS [ORCMATALTURA],MIN(ORCDET.ORCDETBASE) AS [orcmatbase],[ORCDET_COMPRIMENTO]*[ORCDET_PRC_COMPRIMENTO] AS [ORCMATCOMPRIMENTO],ORCDET.ORCDETCORPESQUISA AS [OrcMatCorPesquisa],NULL AS [ORCMATDESCONTO],MIN(ORCDET.ORCDET_GRUPO) AS [OrcMatGrupo],[ORCDET_PROFUNDIDADE]*[ORCDET_PRC_LARGURA] AS [ORCMATLARGURA],NULL AS [orcmatlista],NULL AS [ORCMATSITUACAO],MIN(ORCDET.ORCDET_SUBGRUPO) AS [OrcMatSubGrupo],NULL AS [PISCOFINSFATOR],NULL AS [PISCOFINSVALOR],NULL AS [PRDORCCHK],NULL AS [preco_fixo],0 AS [PISFATOR],0 AS [COFINSFATOR],NULL AS [ROYALTIES_CALCULO],NULL AS [CUSTO_CALCULO],NULL AS [REPASSE_CALCULO],NULL AS [FRETE_CALCULO],NULL AS [INDICE_COMPRA],NULL AS [INDICE_FATURAMENTO],NULL AS [IPI_NAO_INCLUSO],ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS ORCMAT_COUNTER FROM ORCDET WHERE ORCDET.NUMEROORCAMENTO = :orcamento AND ORCDET.ORCDET_ITEM = :item GROUP BY ORCDET.NUMEROORCAMENTO, ORCDET.ORCDET_CODIGO, ORCDET.ORCDETCORPESQUISA, ORCDET.ORCDET_PESO, [ORCDET_COMPRIMENTO]*[ORCDET_PRC_COMPRIMENTO], [ORCDET_ALTURA]*[ORCDET_PRC_ALTURA], [ORCDET_PROFUNDIDADE]*[ORCDET_PRC_LARGURA], ORCDET.ORCDETBASE, ORCDET_PRC_COMPRIMENTO, ORCDET_PRC_ALTURA, ORCDET_PRC_LARGURA", nativeQuery=true)
    List<OrcMat> findAllByNumeroOrcamentoAndOrcdetItem(@Param("orcamento") String orcamento, @Param("item") String item);

}